DoAnCoSo/Areas/Admin/Controllers/ConversationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAnCoSo.Models;
namespace DoAnCoSo.Areas.Admin.Controllers
{
    public class ConversationController : Controller
    {
        private AspNetUserRoleModel dbContext = new AspNetUserRoleModel();

        // Action để hiển thị danh sách các cuộc trò chuyện
        public ActionResult Index()
        {
            var conversations = dbContext.Messages.ToList();
            return View(conversations);
        }

        // Action để trả lời tin nhắn từ một người dùng cụ thể
        public ActionResult Reply(int messageId)
        {
            var message = dbContext.Messages.FirstOrDefault(m => m.Id == messageId);
            if (message == null)
            {
                return HttpNotFound();
            }

            return View(message);
        }


        [HttpPost]
        public ActionResult Reply(Message message)
        {
            if (ModelState.IsValid)
            {
                using (var dbContext = new AspNetUserRoleModel())
                {
                    var existingMessage = dbContext.Messages.Find(message.Id);
                    if (existingMessage != null)
                    {
                        existingMessage.ReplyMessage = message.ReplyMessage;
                        dbContext.SaveChanges();
                    }
                }

                return RedirectToAction("Index");
            }

            // Nếu dữ liệu không hợp lệ, quay trở lại view "Reply" với model để hiển thị thông báo lỗi
            return View(message);
        }

    }
}

DoAnCoSo/Areas/Admin/Views/Conversation/Index.cshtml
@model List<DoAnCoSo.Models.Message>

@{
    ViewBag.Title = "Conversation List";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<h2>Conversation List</h2>

<table class="table">
    <thead>
        <tr>
            <th>Sender</th>
            <th>Message</th>
            <th>Sent Time</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var message in Model)
        {
            <tr>
                <td>@message.Sender</td>
                <td>@message.MessageText</td>
                <td>@message.SentTime</td>
                <td>
                    @Html.ActionLink("Reply", "Reply", new { messageId = message.Id }, new { @class = "btn btn-primary" })
                </td>
            </tr>
        }
    </tbody>
</table>

DoAnCoSo/Areas/Admin/Views/Conversation/Reply.cshtml
@model DoAnCoSo.Models.Message

@{
    ViewBag.Title = "Reply";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<h2>Reply</h2>

<div>
    <strong>Sender:</strong> @Model.Sender
</div>

<div>
    <strong>Message:</strong> @Model.MessageText
</div>

<div>
    <strong>Sent Time:</strong> @Model.SentTime
</div>

<hr />

@if (!string.IsNullOrEmpty(Model.ReplyMessage))
{
    <h4>Admin Reply:</h4>

    <div>
        @Model.ReplyMessage
    </div>

    <hr />
}

<h4>Reply to @Model.Sender:</h4>

@using (Html.BeginForm("Reply", "Conversation", FormMethod.Post))
{
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.ReplyMessage)
        @Html.TextAreaFor(model => model.ReplyMessage, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.ReplyMessage)
    </div>

    <div class="form-group">
        <input type="submit" value="Send Reply" class="btn btn-primary" />
    </div>
}