DoAnCoSo/Models/Barbers.cs
namespace DoAnCoSo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Barbers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Barbers()
        {
            Appointments = new HashSet<Appointments>();
        }

        [Key]
        public int BarberId { get; set; }

        [StringLength(256)]
        public string BarberName { get; set; }

        [StringLength(256)]
        public string Image { get; set; }

        [StringLength(256)]
        public string Description { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointments> Appointments { get; set; }
    }
}

DoAnCoSo/Areas/Admin/Controllers/BarbersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoAnCoSo.Models;

namespace DoAnCoSo.Areas.Admin.Controllers
{
    public class BarbersController : Controller
    {
        private BookingModelContext db = new BookingModelContext();

        // GET: Admin/Barbers
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(db.Barbers.ToList());
        }
        [Authorize(Roles = "Admin")]
        // GET: Admin/Barbers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Barbers barbers = db.Barbers.Find(id);
            if (barbers == null)
            {
                return HttpNotFound();
            }
            return View(barbers);
        }
        [Authorize(Roles = "Admin")]
        // GET: Admin/Barbers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Barbers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BarberId,BarberName,Image,Description")] Barbers barbers, HttpPostedFileBase imageFile)
        {
            if (ModelState.IsValid)
            {
                if (imageFile != null && imageFile.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(imageFile.FileName);
                    var filePath = Path.Combine(Server.MapPath("~/ListImages/Barbers"), fileName);
                    imageFile.SaveAs(filePath);

                    barbers.Image = fileName; // Lưu đường dẫn ảnh trong đối tượng Barbers
                }

                db.Barbers.Add(barbers);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(barbers);
        }

        [Authorize(Roles = "Admin")]
        // GET: Admin/Barbers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Barbers barbers = db.Barbers.Find(id);
            if (barbers == null)
            {
                return HttpNotFound();
            }
            return View(barbers);
        }

        // POST: Admin/Barbers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BarberId,BarberName,Image,Description")] Barbers barbers, HttpPostedFileBase imageFile)
        {
            if (ModelState.IsValid)
            {
                if (imageFile != null && imageFile.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(imageFile.FileName);
                    var filePath = Path.Combine(Server.MapPath("~/ListImages/Barbers"), fileName);
                    imageFile.SaveAs(filePath);

                    barbers.Image = fileName; // Lưu đường dẫn ảnh mới trong đối tượng Barbers
                }

                db.Entry(barbers).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(barbers);
        }

        [Authorize(Roles = "Admin")]
        // GET: Admin/Barbers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Barbers barbers = db.Barbers.Find(id);
            if (barbers == null)
            {
                return HttpNotFound();
            }
            return View(barbers);
        }

        // POST: Admin/Barbers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Barbers barbers = db.Barbers.Find(id);
            if (barbers == null)
            {
                return HttpNotFound();
            }
            db.Barbers.Remove(barbers);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoAnCoSo/Controllers/BarbersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAnCoSo.Models;
namespace DoAnCoSo.Controllers
{
    public class BarbersController : Controller
    {
        // GET: Barbers
        public ActionResult Index()
        {
            var context = new BookingModelContext();
            var barbers = context.Barbers.ToList();
            return View(barbers);
        }
    }
}

DoAnCoSo/Areas/Admin/Views/Barbers/Create.cshtml
@model DoAnCoSo.Models.Barbers

@using (Html.BeginForm("Create", "Barbers", FormMethod.Post, new { id = "addRowForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h3>Thêm Thợ Cắt Tóc</h3>
        <h5>Nhập Thông Tin Thợ Cắt Tóc Cần Thêm</h5>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <h3>Tên Thợ Cắt Tóc</h3>
            <div class="col-md-10">
                @Html.EditorFor(model => model.BarberName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BarberName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <h3>Ảnh Thợ Cắt Tóc</h3>
            <div class="col-md-10">
                <input type="file" name="imageFile" id="imageFile" class="form-control" />
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <h3>Mô Tả Thợ Cắt Tóc</h3>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="modal-footer no-bd">
            <button type="submit" id="addRowButton" class="btn btn-primary">Thêm</button>
            <button type="button" class="btn btn-danger" data-dismiss="modal">Thoát</button>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DoAnCoSo/Areas/Admin/Views/Barbers/Delete.cshtml
@model DoAnCoSo.Models.Barbers


<h3>Bạn có chắc chắn muốn xoá thợ cắt tóc không?</h3>
<div>
    <h4>Xoá Thợ Cắt Tóc</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên Thợ Cắt Tóc
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BarberName)
        </dd>

        <dt>
            Ảnh Thợ Cắt Tóc
        </dt>

        <dd>           
            <div class="avatar avatar-xxl">
            <img src="@Url.Content("~/ListImages/Barbers/" + Html.DisplayFor(modelItem => Model.Image))" alt="..." class="avatar-img rounded">
            </div>            
        </dd>

        <dt>
            Mô Tả Thợ Cắt Tóc
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
    @using (Html.BeginForm("Delete", "Barbers", new { id = Model.BarberId }, FormMethod.Post, new { id = "deleteForm" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <button type="submit" class="btn btn-success" id="alert_demo_7">Xoá</button>
        </div>
    }




</div>

DoAnCoSo/Areas/Admin/Views/Barbers/Details.cshtml
@model DoAnCoSo.Models.Barbers

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Barbers</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BarberName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BarberName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BarberId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DoAnCoSo/Areas/Admin/Views/Barbers/Edit.cshtml
@model DoAnCoSo.Models.Barbers

@{
    ViewBag.Title = "Edit";
}


@using (Html.BeginForm("Edit", "Barbers", new { id = Model.BarberId }, FormMethod.Post, new { id = "editRowForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Chỉnh Sửa Thông Tin Thợ Cắt Tóc</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BarberId)

        <div class="form-group">
            <h3>Tên Thợ Cắt Tóc</h3>
            <div class="col-md-10">
                @Html.EditorFor(model => model.BarberName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BarberName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <h3>Ảnh Thợ Cắt Tóc</h3>
            <div class="col-md-10">
                <input type="file" name="imageFile" />
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <h3>Mô Tả Thợ Cắt Tóc</h3>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DoAnCoSo/Areas/Admin/Views/Barbers/Index.cshtml
@model IEnumerable<DoAnCoSo.Models.Barbers>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css">
<script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>

<div class="page-inner">
    <div class="page-header">
        <h4 class="page-title">Quản Lý Thợ Cắt Tóc</h4>
        <ul class="breadcrumbs">
            <li class="nav-home">
                <a href="/Admin/Home/Index">
                    <i class="flaticon-home"></i>
                </a>
            </li>
            <li class="separator">
                <i class="flaticon-right-arrow"></i>
            </li>
            <li class="nav-item">
                <a href="/Admin/Barbers/Index">Thợ Cắt Tóc</a>
            </li>
        </ul>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex align-items-center">
                        <h4 class="card-title">Thêm Thợ Cắt Tóc</h4>
                        <button class="btn btn-primary btn-round ml-auto" data-toggle="modal" data-target="#addRowModal">
                            <i class="fa fa-plus"></i>
                            Thêm Mới
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="modal fade" id="addRowModal" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header no-bd">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    @Html.Partial("Create", new DoAnCoSo.Models.Barbers())
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table id="add-row" class="display table table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>Tên</th>
                                    <th>Ảnh</th>
                                    <th>Mô Tả</th>
                                    <th style="width: 10%">Hành Động</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr data-barbers-id="@item.BarberId">

                                        <td>@Html.DisplayFor(modelItem => item.BarberName)</td>
                                        <td>
                                            <div class="avatar avatar-lg">
                                                <img src="@Url.Content("~/ListImages/Barbers/" + Html.DisplayFor(modelItem => item.Image))" alt="..." class="avatar-img rounded-circle">
                                            </div>
                                        </td>

                                        <td>@Html.DisplayFor(modelItem => item.Description)</td>
                                        <td>
                                            <div class="form-button-action">
                                                <button type="button" class="btn btn-link btn-primary btn-lg btn-edit" data-toggle="modal" data-target="#editPopup_@item.BarberId" data-toggle="tooltip" title="Edit Task">
                                                    <i class="fa fa-edit"></i>
                                                </button>
                                                <button type="button" class="btn btn-link btn-danger btn-lg btn-delete" data-toggle="modal" data-target="#deletePopup_@item.BarberId" data-toggle="tooltip" title="Remove">
                                                    <i class="fa fa-times"></i>
                                                </button>
                                            </div>
                                            <!-- Popup Chỉnh sửa -->
                                            <div id="editPopup_@item.BarberId" class="modal fade" tabindex="-1" role="dialog">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                <span aria-hidden="true">&times;</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <!-- Nội dung của trang Edit -->
                                                            @Html.Partial("Edit", item)
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <!-- Popup Xóa -->
                                            <div id="deletePopup_@item.BarberId" class="modal fade" tabindex="-1" role="dialog">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                <span aria-hidden="true">&times;</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <!-- Nội dung của trang Delete -->
                                                            @Html.Partial("Delete", item)
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>


                                        </td>
                                    </tr>
                            }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @section scripts {
        <script>
            $('#add-row').DataTable();
            $(document).ready(function () {
                $('#addRowButton').click(function () {
                    $('#add-row').dataTable().fnAddData([
                        $("#addName").val(),
                        $("#addPosition").val(),
                        $("#addOffice").val(),
                        action
                    ]);
                    $('#addRowModal').modal('hide');

                });
            });
        </script>
    }