DoAnCoSo/Models/Seat.cs
namespace DoAnCoSo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Seat")]
    public partial class Seat
    {
        [Key]
        public int SeatId { get; set; }

        public int? SeatNumber { get; set; }

        public int? Availability { get; set; }
    }
}

DoAnCoSo/Areas/Admin/Controllers/SeatsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoAnCoSo.Models;

namespace DoAnCoSo.Areas.Admin.Controllers
{
    public class SeatsController : Controller
    {
        private BookingModelContext db = new BookingModelContext();
        [Authorize(Roles = "Admin")]
        // GET: Admin/Seats
        public ActionResult Index()
        {
            return View(db.Seats.ToList());
        }
        [Authorize(Roles = "Admin")]
        // GET: Admin/Seats/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seat seat = db.Seats.Find(id);
            if (seat == null)
            {
                return HttpNotFound();
            }
            return View(seat);
        }
        [Authorize(Roles = "Admin")]
        // GET: Admin/Seats/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Seats/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SeatId,SeatNumber,Availability")] Seat seat)
        {
            if (ModelState.IsValid)
            {
                db.Seats.Add(seat);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(seat);
        }
        [Authorize(Roles = "Admin")]
        // GET: Admin/Seats/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seat seat = db.Seats.Find(id);
            if (seat == null)
            {
                return HttpNotFound();
            }
            return View(seat);
        }

        // POST: Admin/Seats/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SeatId,SeatNumber,Availability")] Seat seat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(seat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(seat);
        }
        [Authorize(Roles = "Admin")]
        // GET: Admin/Seats/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seat seat = db.Seats.Find(id);
            if (seat == null)
            {
                return HttpNotFound();
            }
            return View(seat);
        }

        // POST: Admin/Seats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Seat seat = db.Seats.Find(id);
            db.Seats.Remove(seat);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoAnCoSo/Areas/Admin/Views/Seats/Create.cshtml
@model DoAnCoSo.Models.Seat

<body>
    @using (Html.BeginForm("Create", "Seats", FormMethod.Post, new { id = "addRowForm" })) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Thêm Ghế</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <h3>Số Ghế</h3>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SeatNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SeatNumber, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <h3>Trạng Thái</h3>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Availability, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Availability, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Tạo" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</body>
</html>

DoAnCoSo/Areas/Admin/Views/Seats/Delete.cshtml
@model DoAnCoSo.Models.Seat


<body>
    <h3>Bạn có chắc chắn muốn xoá chỗ ngồi?</h3>
    <div>
        <h4>Xoá Ghế</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
               Số Ghế
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SeatNumber)
            </dd>
    
            <dt>
                Trạng Thái
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Availability)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm("Delete", "Seats", new { id = Model.SeatId }, FormMethod.Post, new { id = "deleteForm" })) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Xoá" class="btn btn-default" />
            </div>
        }
    </div>
</body>
</html>

DoAnCoSo/Areas/Admin/Views/Seats/Details.cshtml
@model DoAnCoSo.Models.Seat

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Seat</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.SeatNumber)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SeatNumber)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Availability)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Availability)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.SeatId }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

DoAnCoSo/Areas/Admin/Views/Seats/Edit.cshtml
@model DoAnCoSo.Models.Seat

<body>
    @using (Html.BeginForm("Edit", "Seats", new { id = Model.SeatId }, FormMethod.Post, new { id = "editForm" }))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Chỉnh sửa</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.SeatId)
    
            <div class="form-group">
                <h3>Số Ghế</h3>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SeatNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SeatNumber, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <h3>Trạng Thái</h3>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Availability, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Availability, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lưu" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</body>
</html>

DoAnCoSo/Areas/Admin/Views/Seats/Index.cshtml
@model IEnumerable<DoAnCoSo.Models.Seat>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/Admin_Layout.cshtml";
}

<div class="page-inner">
    <div class="page-header">
        <h4 class="page-title">Quản Lý Chỗ Ngồi</h4>
        <ul class="breadcrumbs">
            <li class="nav-home">
                <a href="/Admin/Home/Index">
                    <i class="flaticon-home"></i>
                </a>
            </li>
            <li class="separator">
                <i class="flaticon-right-arrow"></i>
            </li>
            <li class="nav-item">
                <a href="/Admin/Seats/Index">Chỗ Ngồi</a>
            </li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex align-items-center">
                        <h4 class="card-title">Thêm Chỗ Ngồi</h4>
                        <button class="btn btn-primary btn-round ml-auto" data-toggle="modal" data-target="#addRowModal">
                            <i class="fa fa-plus"></i>
                            Thêm
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    <!-- Modal -->
                    <div class="modal fade" id="addRowModal" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header no-bd">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    @Html.Partial("Create", new DoAnCoSo.Models.Seat())
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <table id="add-row" class="display table table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>Số Ghế</th>
                                    <th>Trạng Thái</th>
                                    <th style="width: 10%">Hành Động</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {

                                    <tr data-barbers-id="@item.SeatId">

                                        <td>@Html.DisplayFor(modelItem => item.SeatNumber)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Availability)</td>
                                        <td>
                                            <div class="form-button-action">
                                                <button type="button" class="btn btn-link btn-primary btn-lg btn-edit" data-toggle="modal" data-target="#editPopup_@item.SeatId" data-toggle="tooltip" title="Edit Task">
                                                    <i class="fa fa-edit"></i>
                                                </button>
                                                <button type="button" class="btn btn-link btn-danger btn-lg btn-delete" data-toggle="modal" data-target="#deletePopup_@item.SeatId" data-toggle="tooltip" title="Remove">
                                                    <i class="fa fa-times"></i>
                                                </button>
                                            </div>
                                            <!-- Popup Chỉnh sửa -->
                                            <div id="editPopup_@item.SeatId" class="modal fade" tabindex="-1" role="dialog">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                <span aria-hidden="true">&times;</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <!-- Nội dung của trang Edit -->
                                                            @Html.Partial("Edit", item)
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <!-- Popup Xóa -->
                                            <div id="deletePopup_@item.SeatId" class="modal fade" tabindex="-1" role="dialog">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                <span aria-hidden="true">&times;</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <!-- Nội dung của trang Delete -->
                                                            @Html.Partial("Delete", item)
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>


                                        </td>
                                    </tr>

                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script>
        $('#add-row').DataTable();
        $(document).ready(function () {
            $('#addRowButton').click(function () {
                $('#add-row').dataTable().fnAddData([
                    $("#addName").val(),
                    $("#addPosition").val(),
                    $("#addOffice").val(),
                    action
                ]);
                $('#addRowModal').modal('hide');

            });
        });
    </script>
}